"""
RAG API schemas — request/response models for the /chat endpoint.
"""

from typing import Optional

from pydantic import BaseModel, Field

from app.schemas.search import SearchHit


class RAGRequest(BaseModel):
    """Request body for POST /api/v1/chat."""

    query: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="Natural language question to answer from indexed documents.",
        examples=["What is Mustapha Idabella's phone number?"],
    )
    top_k: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Number of document chunks to retrieve for context.",
    )
    score_threshold: Optional[float] = Field(
        default=0.3,
        ge=0.0,
        le=1.0,
        description="Minimum similarity score for retrieved chunks.",
    )


class RAGResponse(BaseModel):
    """Response body for POST /api/v1/chat."""

    query: str = Field(description="The original user query.")
    answer: str = Field(description="Natural language answer generated by Gemini.")
    sources: list[SearchHit] = Field(
        description="Document chunks used as context for generation."
    )
    total_sources: int = Field(description="Number of source chunks used.")
    processing_time_ms: float = Field(
        description="Total processing time in milliseconds (retrieval + generation)."
    )
